### ISSUE TITLE
Mods will be unable to be downloaded if HTTPS certification is invalid

### ISSUE THREAD

**Issue by gengyunmaster** [HRudyPlayZ/MCInstanceLoader#3]
Hello! I found some problems in automatically installing a modpack by MC Instance Loader. Many mods were unable to be downloaded if the certification of the download site is invalid. Can you add a configuration option to be able to trust all the sites to avoid this problem? Thank you very much! Errors in the log are like this:

[02:10:12] [Server thread/INFO] [MCInstance Loader/mcinstanceloader]: Downloading HardcoreEnderExpansion... (632/743 resources)
[02:10:12] [Server thread/INFO] [MCInstance Loader/mcinstanceloader]: An error occured while downloading the file, trying again...
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.ssl.Alert.createSSLException(Alert.java:131)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:377)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1392)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1300)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:435)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1488)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.security.AccessController.doPrivileged(Native Method)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1487)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.hrudyplayz.mcinstanceloader.utils.WebHelper.downloadFile(WebHelper.java:59)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.hrudyplayz.mcinstanceloader.utils.WebHelper.downloadFile(WebHelper.java:77)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.hrudyplayz.mcinstanceloader.utils.WebHelper.downloadFile(WebHelper.java:34)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.hrudyplayz.mcinstanceloader.resources.ResourceObject.downloadFile(ResourceObject.java:467)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.hrudyplayz.mcinstanceloader.Main.downloadResources(Main.java:443)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.hrudyplayz.mcinstanceloader.Main.secondPhase(Main.java:69)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.hrudyplayz.mcinstanceloader.ForgeMod.preInit(ForgeMod.java:27)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:456)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:323)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.validator.Validator.validate(Validator.java:271)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:315)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:223)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	... 60 more
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:451)
[02:10:13] [Server thread/INFO] [STDERR/mcinstanceloader]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	... 66 more
[02:10:13] [Server thread/ERROR] [MCInstance Loader/mcinstanceloader]: Error while downloading HardcoreEnderExpansion. (There was an issue writing to file.)
[02:10:13] [Server thread/INFO] [MCInstance Loader/mcinstanceloader]: Failed to install the mcinstance file!
[02:10:13] [Server thread/DEBUG] [FML/mcinstanceloader]: Bar Step: MCInstance: Downloading resource - HardcoreEnderExpansion took 1.382s

**Comment by HRudyPlayZ** [comment]
Will work on it in v3.0, it's probably gonna be as a config to ignore HTTPS certificates. Didn't even know HTTPUrlConnection fully handled certificates xD

**Comment by HRudyPlayZ** [comment]
Seems to be fixed in 2.7, don't hesitate to recreate the issue if it still happens.
The fix involves enabling the certificate bypass in the config.
